apiVersion: apps/v1
kind: Deployment
metadata:
  name: blood-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blood-frontend
  template:
    metadata:
      labels:
        app: blood-frontend
    spec:
      containers:
        - name: frontend
          image: blood-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blood-frontend
spec:
  type: LoadBalancer
  selector:
    app: blood-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
